### ISSUE TITLE
ContainerValueReader Unable to read TimeStamp

### ISSUE THREAD

**Issue by sc6l6d3v** [Kirill5k/mongo4cats#22]
The JsonDocumentFindAndUpdate.scala example throws an exception because it is unable to map the TimeStamp type which is unimplemented in  readBsonValue() l. 92: 

![image](https://user-images.githubusercontent.com/8728152/212217887-4430aef6-4a26-4686-ad31-7195876d5ab7.png)

I can shift to a Date_Time in the meanwhile but just wondering if you're planning on implementing this anytime soon?

org.bson.BsonInvalidOperationException: ReadBSONType can only be called when State is TYPE, not when State is VALUE.
	at org.bson.AbstractBsonReader.throwInvalidState(AbstractBsonReader.java:668)
	at org.bson.BsonBinaryReader.readBsonType(BsonBinaryReader.java:88)
	at mongo4cats.codecs.ContainerValueReader$.go$1(ContainerValueReader.scala:32)
	at mongo4cats.codecs.ContainerValueReader$.readBsonDocument(ContainerValueReader.scala:40)
	at mongo4cats.codecs.DocumentCodec.decode(DocumentCodecProvider.scala:37)
	at mongo4cats.codecs.DocumentCodec.decode(DocumentCodecProvider.scala:25)

**Comment by Kirill5k** [comment]
On Mongodb website it is stated that timestamp is for internal use only and it is suggested to use regular date time instead. Because of that I never got around at implementing it.

Nevertheless, I've updated `ContainerValueReader` and `ContainerValueWriter` just now to be able to handle those so this shouldn't be a problem anymore.

I'll do a release later today.

**Comment by Kirill5k** [comment]
Update your dependency to `0.6.6` and it'll work 👍

**Comment by sc6l6d3v** [comment]
Thanks for the quick fix. I did move to date time so workaround. Will 
pull latest change.
